"""Seed events.json with real events observed during the venue recon phase.

This is a one-time bootstrap so the page has data even before the first
real cron run. Once `aggregate.py` runs, it will overwrite events.json
with freshly scraped data.

Source: events extracted from the public agenda pages of each venue
during the project setup (April 2026). Run with: `python seed.py`.
"""
from __future__ import annotations
import json
from datetime import date, datetime
from pathlib import Path

from scrapers import Event


SEED = [
    # --- LE SUCRE ----------------------------------------------------------
    Event("Le Sucre", "le-sucre", "High-Lo présente : DAKEEZ", "DAKEEZ", "concert",
          "2026-04-30", None, None,
          "https://le-sucre.eu/events/high-lo-presente-dakeez/", None),
    Event("Le Sucre", "le-sucre", "club x Soeurs Malsaines",
          "Brascht · Harey Izé · Kampire · Le Saint · Tasmania · Vik-ing · Yamacassy", "club",
          "2026-05-01", None, None,
          "https://le-sucre.eu/events/club-x-soeurs-malsaines-3/", None),
    Event("Le Sucre", "le-sucre", "EXT.12 : Nuits sonores x The Absolut Creation Company",
          "Call Super · DJ Monique · Jen Cardini · LSDXOXO · RONI · Satine · TSVI", "club",
          "2026-05-02", None, None,
          "https://le-sucre.eu/events/nuits-sonores-x-tacc-absolut/", None),
    Event("Le Sucre", "le-sucre", "S.society x TSSRCT", "Exuvie · Hadone · UFO95", "club",
          "2026-05-03", None, None,
          "https://le-sucre.eu/events/s-society-x-tssrct/", None),
    Event("Le Sucre", "le-sucre", "Magic Mardi", "Kauzie · Jo Kovaa · Shakti", "club",
          "2026-05-05", None, None,
          "https://le-sucre.eu/events/magic-mardi-76/", None),
    Event("Le Sucre", "le-sucre", "club x Virtual Forest",
          "Andy Martin · Emily Jeanne · Jacky Jeane · Natural Limit · Solma · Fluid Matter", "club",
          "2026-05-07", None, None,
          "https://le-sucre.eu/events/club-x-virtual-forests-5-ans/", None),
    Event("Le Sucre", "le-sucre", "club x crush",
          "Jäde · Jlise · Louis Romeo · S!rene", "club",
          "2026-05-08", None, None,
          "https://le-sucre.eu/events/club-x-crush/", None),
    Event("Le Sucre", "le-sucre", "club", "Alarico · Elise Massoni · Dave Alyan", "club",
          "2026-05-09", None, None,
          "https://le-sucre.eu/events/club-48/", None),
    Event("Le Sucre", "le-sucre", "S.society", "Hyas · Mézigue", "club",
          "2026-05-10", None, None,
          "https://le-sucre.eu/events/s-society-x-tssrct-2/", None),
    Event("Le Sucre", "le-sucre", "Nuits sonores — Nuit 1",
          "aamourocean x PLEUR (live) · amne · Lisa More · No Plexus (live A/V) · notinbed", "club",
          "2026-05-13", None, None,
          "https://le-sucre.eu/events/night-1/", None),
    Event("Le Sucre", "le-sucre", "Nuits sonores — Nuit 2",
          "Dasha Rush · JakoJako · Rødhåd · UFO95", "club",
          "2026-05-14", None, None,
          "https://le-sucre.eu/events/nuit-2/", None),
    Event("Le Sucre", "le-sucre", "Nuits sonores — Nuit 3",
          "Cardozo (live) · DJPOMPOMPOM · DJ Travella · LinLin (live) · Uzi Freyja (live)", "club",
          "2026-05-15", None, None,
          "https://le-sucre.eu/events/nuits-sonores-nuit-3-2/", None),
    Event("Le Sucre", "le-sucre", "Nuits sonores — Nuit 4",
          "Benedikt Frey · Jokkoo Collective · Noémi Büchi · NVST · Powell (live)", "club",
          "2026-05-16", None, None,
          "https://le-sucre.eu/events/nuits-sonores-nuit-4-2/", None),
    Event("Le Sucre", "le-sucre", "club x Asian Core",
          "Animistic Beliefs · FEIYI · To Van Kao", "club",
          "2026-05-29", None, None,
          "https://le-sucre.eu/events/club-x-asian-core/", None),
    Event("Le Sucre", "le-sucre", "club", "Karissa · SALOME · Toccororo", "club",
          "2026-05-30", None, None,
          "https://le-sucre.eu/events/karissa-salome-tocorroro/", None),
    Event("Le Sucre", "le-sucre", "S.society", "Elix · Mischluft", "club",
          "2026-05-31", None, None,
          "https://le-sucre.eu/events/s-society-149/", None),
    Event("Le Sucre", "le-sucre", "High-Lo présente : Bianca Costa", "Bianca Costa", "concert",
          "2026-11-14", None, None,
          "https://le-sucre.eu/events/high-lo-presente-12/", None),
    Event("Le Sucre", "le-sucre", "Concert : Spider Zed", "Spider Zed", "concert",
          "2026-11-20", None, None,
          "https://le-sucre.eu/events/concert-4/", None),

    # --- LES SUBSISTANCES --------------------------------------------------
    Event("Les Subsistances", "les-subs", "SUBS-VISITE", "Visite historique", "visite",
          "2026-05-06", None, "18:30",
          "https://www.les-subs.com/evenement/subs-visite/", None),
    Event("Les Subsistances", "les-subs", "Prova", "Waël Ali & Simon Dubois", "théâtre",
          "2026-05-07", None, "19:00",
          "https://www.les-subs.com/evenement/prova/", None),
    Event("Les Subsistances", "les-subs", "Zeid Hamdan Live", None, "musique",
          "2026-05-07", None, "20:30",
          "https://www.les-subs.com/evenement/zeid-hamdan-live/", None),
    Event("Les Subsistances", "les-subs", "Dressing Room",
          "Bissane Al Charif & Hala Omran", "théâtre",
          "2026-05-08", None, "19:00",
          "https://www.les-subs.com/evenement/dressing-room/", None),
    Event("Les Subsistances", "les-subs", "ARAB FUNK",
          "Shnsho & KhelKhal (ZabZab Lab)", "dj set",
          "2026-05-08", None, "20:00",
          "https://www.les-subs.com/evenement/arab-funk/", None),
    Event("Les Subsistances", "les-subs", "Cruise my mountain", "The Darvish", "danse",
          "2026-05-08", None, "21:00",
          "https://www.les-subs.com/evenement/cruise-my-mountain/", None),
    Event("Les Subsistances", "les-subs", "Absurd Hero", "Roman Škadra", "cirque",
          "2026-05-09", None, "16:00",
          "https://www.les-subs.com/evenement/absurd-hero/", None),
    Event("Les Subsistances", "les-subs", "Absurd Hero", "Roman Škadra", "cirque",
          "2026-05-09", None, "18:30",
          "https://www.les-subs.com/evenement/absurd-hero/", None),
    Event("Les Subsistances", "les-subs", "QUEENS AGAINST BORDERS", None, "performance",
          "2026-05-09", None, "20:00",
          "https://www.les-subs.com/evenement/queens-against-borders/", None),
    Event("Les Subsistances", "les-subs", "Absurd Hero", "Roman Škadra", "cirque",
          "2026-05-10", None, "16:00",
          "https://www.les-subs.com/evenement/absurd-hero/", None),
    Event("Les Subsistances", "les-subs", "Boum Enfants + Atelier Mix", "Chouf", "dj set",
          "2026-05-10", None, "17:00",
          "https://www.les-subs.com/evenement/boum-enfants/", None),
    Event("Les Subsistances", "les-subs", "Baby Volcano",
          "Concert spécial Nuits sonores", "performance",
          "2026-05-15", None, "20:00",
          "https://www.les-subs.com/evenement/baby-volcano/", None),
    Event("Les Subsistances", "les-subs", "Baby Volcano",
          "Concert spécial Nuits sonores", "performance",
          "2026-05-16", None, "20:00",
          "https://www.les-subs.com/evenement/baby-volcano/", None),
    Event("Les Subsistances", "les-subs", "Si la langue fourche",
          "Conversation avec No Anger & Elisabeth Lebovici", "performance",
          "2026-05-21", None, "19:00",
          "https://www.les-subs.com/evenement/si-la-langue-fourche/", None),
    Event("Les Subsistances", "les-subs", "THE DARK (Prélude folk)",
          "Marie-Pierre Brébant & Gabriel Gauthier", "musique",
          "2026-05-22", None, "19:00",
          "https://www.les-subs.com/evenement/the-dark/", None),
    Event("Les Subsistances", "les-subs", "Nocturne (Parade)", "Phia Ménard", "danse",
          "2026-05-26", None, "19:00",
          "https://www.les-subs.com/evenement/nocturne-parade/", None),
    Event("Les Subsistances", "les-subs", "Nocturne (Parade)", "Phia Ménard", "danse",
          "2026-05-27", None, "19:00",
          "https://www.les-subs.com/evenement/nocturne-parade/", None),
    Event("Les Subsistances", "les-subs", "Ce que le ciel ne sait pas",
          "Feda Wardak, Saïdo Lehlouh, Deena Abdelwahed", "danse",
          "2026-06-04", None, "21:30",
          "https://www.les-subs.com/evenement/ce-que-le-ciel-ne-sait-pas/", None),
    Event("Les Subsistances", "les-subs", "Rodéo", "Léa Drouet", "danse",
          "2026-06-11", None, "19:00",
          "https://www.les-subs.com/evenement/rodeo/", None),
    Event("Les Subsistances", "les-subs", "Mirages et tendresses", "Ivana Müller", "danse",
          "2026-06-11", None, "21:00",
          "https://www.les-subs.com/evenement/mirages-et-tendresses/", None),
    Event("Les Subsistances", "les-subs", "Dance People", "Maqamat", "danse",
          "2026-06-19", None, "20:00",
          "https://www.les-subs.com/evenement/dance-people/", None),
    Event("Les Subsistances", "les-subs", "LE SACRE DU PRINTEMPS", "Roger Bernat", "danse",
          "2026-06-20", None, "19:00",
          "https://www.les-subs.com/evenement/le-sacre-du-printemps/", None),
    Event("Les Subsistances", "les-subs", "Fête de la musique",
          "The Big Dance Jam · Nader · Founé · Zeid Hamdan", "musique",
          "2026-06-21", None, "20:00",
          "https://www.les-subs.com/evenement/fete-de-la-musique/", None),
    Event("Les Subsistances", "les-subs", "Shangwe, le bal", "Wanjiru Kamuyu", "danse",
          "2026-07-14", None, "20:30",
          "https://www.les-subs.com/evenement/shangwe-le-bal/", None),

    # --- MARCHÉ GARE -------------------------------------------------------
    Event("Marché Gare", "marche-gare", "IT IT ANITA + La Jungle", None, "noise rock",
          "2026-04-30", None, "20:30",
          "https://marchegare.fr/agenda/it-it-anita", None),
    Event("Marché Gare", "marche-gare", "Clo + Rroy + Alyosha", "Concert du Labo", "concert",
          "2026-05-06", None, "20:30",
          "https://marchegare.fr/agenda/clo-rroy-alyosha", None),
    Event("Marché Gare", "marche-gare", "Bandit Bandit", None, "pop-rock",
          "2026-05-07", None, "20:30",
          "https://marchegare.fr/agenda/bandit-bandit", None),
    Event("Marché Gare", "marche-gare", "Paledusk + Knosis + Greyhaven + Headwreck", None, "metal",
          "2026-05-16", None, "19:00",
          "https://marchegare.fr/agenda/paledusk", None),
    Event("Marché Gare", "marche-gare", "Claire Days + Citron Sucré + JIA",
          "20 ans du Marché Gare — Concert du Labo anniversaire", "concert",
          "2026-05-21", None, "20:30",
          "https://marchegare.fr/agenda/claire-days-citron-sucre-jia", None),
    Event("Marché Gare", "marche-gare", "Forever Pavot", None, "pop électro",
          "2026-05-28", None, "20:30",
          "https://marchegare.fr/agenda/forever-pavot", None),
    Event("Marché Gare", "marche-gare", "The Guru Guru + Psychonaut + Occult Hand Order",
          None, "post-metal",
          "2026-06-04", None, "20:30",
          "https://marchegare.fr/agenda/psychonaut", None),
    Event("Marché Gare", "marche-gare", "Future Palace", None, "post-hardcore",
          "2026-10-10", None, "20:30",
          "https://marchegare.fr/agenda/future-palace", None),
    Event("Marché Gare", "marche-gare", "Ferdi", None, "jazz",
          "2026-11-07", None, "20:00",
          "https://marchegare.fr/agenda/ferdi", None),

    # --- RADIANT-BELLEVUE (sample from JDS aggregator) ---------------------
    Event("Radiant-Bellevue", "radiant-bellevue", "Tania Dutel — Nouveau spectacle",
          None, "humour",
          "2026-04-30", None, "20:30",
          "https://radiant-bellevue.fr/", None),
    Event("Radiant-Bellevue", "radiant-bellevue", "Renan Luce", None, "chanson française",
          "2026-11-26", None, "20:00",
          "https://radiant-bellevue.fr/", None),
    Event("Radiant-Bellevue", "radiant-bellevue", "Marillion — Tournée", None, "rock",
          "2026-11-29", None, "19:00",
          "https://radiant-bellevue.fr/", None),
    Event("Radiant-Bellevue", "radiant-bellevue", "La Grande Sophie — Tournée",
          None, "chanson française",
          "2026-12-02", None, "20:30",
          "https://radiant-bellevue.fr/", None),
    Event("Radiant-Bellevue", "radiant-bellevue", "Garou — Solo", None, "chanson française",
          "2026-12-04", None, "20:30",
          "https://radiant-bellevue.fr/", None),
    Event("Radiant-Bellevue", "radiant-bellevue", "Ménopause", None, "théâtre",
          "2026-04-20", None, "20:30",
          "https://radiant-bellevue.fr/", None),
    Event("Radiant-Bellevue", "radiant-bellevue", "Murmuration Level 2",
          "Hip-hop, ballet et arts martiaux", "danse",
          "2026-12-12", None, "20:30",
          "https://radiant-bellevue.fr/", None),
    Event("Radiant-Bellevue", "radiant-bellevue", "Stephan Eicher — Poussière d'Or Tour",
          None, "chanson française",
          "2026-11-24", None, "20:30",
          "https://radiant-bellevue.fr/", None),
]


def main():
    today = date.today().isoformat()
    upcoming = [e for e in SEED if e.date_start >= today]
    upcoming.sort(key=lambda e: (e.date_start, e.time or "00:00", e.venue))

    payload = {
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "count": len(upcoming),
        "events": [e.to_dict() for e in upcoming],
    }
    out = Path(__file__).parent / "events.json"
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(upcoming)} seed events to {out}")


if __name__ == "__main__":
    main()
